name: Go
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      CGO_ENABLED: 0
    steps:

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: go mod download
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

  build-docker:
    name: Build Multi-Arch Docker Images
    needs: build
    strategy:
      matrix:
        include:
          - platform: amd64
            runner: ubuntu-latest
          # need to sort out the merging: https://github.com/docker/build-push-action/issues/1287
          # - platform: arm64
          #   runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/lstoll/k8soidcpublisher
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/${{ matrix.platform }}

    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build and push ${{ matrix.platform }}
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/${{ matrix.platform }}
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
