name: Go
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

# rebuild: A

jobs:
  build:
    uses: lstoll/actions-workflows/.github/workflows/go-docker.yaml@main
    with:
      image: ghcr.io/lstoll/k8soidcpublisher
    permissions:
      contents: read
      packages: write
