name: Go
on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

env:
  REGISTRY_IMAGE: ghcr.io/lstoll/k8soidcpublisher

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
      id: go

    - name: go mod download
      run: |
        go mod download

    - name: Test
      run: |
        go test ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: stable
      id: go

    - name: go mod download
      run: |
        go mod download

    - name: Lint
      uses: golangci/golangci-lint-action@v8
      with:
        version: latest

  build-docker:
    name: Build Multi-Arch Docker Images
    needs:
    - test
    - lint
    strategy:
      matrix:
        include:
          - platform: amd64
            runner: ubuntu-latest
          # need to sort out the merging: https://github.com/docker/build-push-action/issues/1287
          - platform: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:

    - name: Prepare
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY_IMAGE }}
        # generate Docker tags based on the following events/attributes
        # tags: |
        #   type=ref,event=branch
        #   type=ref,event=pr
        #   type=semver,pattern={{version}}
        #   type=semver,pattern={{major}}.{{minor}}
        #   type=semver,pattern={{major}}
        #   type=sha

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/${{ matrix.platform }}

    - name: Login to GHCR
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build and push ${{ matrix.platform }}
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: linux/${{ matrix.platform }}
        push: ${{ github.event_name != 'pull_request' }}
        labels: ${{ steps.meta.outputs.labels }}
        tags: ${{ env.REGISTRY_IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=image,push-by-digest=true,name-canonical=true,push=true
        provenance: false # this doesn't work with merging multi-arch at the moment

    - name: Export digest
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${{ steps.build.outputs.digest }}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

    - name: Upload digest
      uses: actions/upload-artifact@v4
      with:
        name: digests-${{ env.PLATFORM_PAIR }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1

  docker-merge:
    name: Merge platform docker images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs:
      - build-docker
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}
